name: datastore_fs
version: 0.1.0
description: A sample web application
dependencies:
  collection: '>=0.9.0 <0.10.0'
  google_oauth2_client: '>=0.3.4 <0.4.0'
  http: '>=0.9.0 <0.11.0'
  logging: any
  quiver: any
dev_dependencies:
  unittest: any
